#!/bin/bash

cp /boot/config.txt /tmp/

FLAGS=""

if [ "$1" == "--only-if-not-set" ]; then
    FLAGS="$1"
    shift
fi

edit-config $FLAGS /tmp/config.txt "$@"

diff /boot/config.txt /tmp/config.txt >/dev/null
if [ $? -eq 1 ]; then
  mount -o remount,rw /boot
  mv /tmp/config.txt /boot/
  mount -o remount,ro /boot
fi
